import { Poppins } from "next/font/google";
import { AppBar, Toolbar, Container, Box, Typography } from "@mui/material";
import ThemeProviderComponent from "./ThemeProvider";
import "./globals.css";

const poppins = Poppins({ 
  subsets: ["latin"],
  weight: ['400', '700']
});

export const metadata = {
  title: "Pantry Tracker",
  description: "Generated by create next app",
};

const Header = () => (
  <Box
    component="header" sx={{
      bgcolor: 'f9f9f9', padding: '1rem',
      textAlign: 'start', paddingLeft: '3rem',
      top:0, width: '100%'
    }}
  >
    <Typography variant="h6" sx={{
      color: 'black', fontWeight: 'bold',
      fontFamily: 'Poppins, sans-serif', fontSize: '1.5rem'
    }}>
      Pantry Tracker
    </Typography>
  </Box>
)

const Footer = () => (
  <Box component="footer" sx={{p:2, textAlign:'center', bgcolor:'#f5f5f5'}}>
    <Typography variant="body2">
    &copy; 2024 Pantry Tracker. All rights reserved.
    </Typography>
  </Box>
)

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className="{poppins.className}">
        <ThemeProviderComponent>
          <Header/>
            <main>{children}</main>
          <Footer/>
        </ThemeProviderComponent>
      </body>
    </html>
  )
}